apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: indexer
spec:
  replicas: 3
  serviceName: indexer
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      labels:
        app: splunk
        role: indexer
    spec:
      volumes:
        - name: boot-config
          configMap:
            name: indexer-boot-config
            items:
              - key: indexer.conf
                path: indexer.conf
      containers:
        - name: indexer
          image: andycunn/splunk-kube
          # image: gcr.io/google_containers/explorer:1.0
          # args: ["-port=8088"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8088
            - containerPort: 8089
            - containerPort: 9997
            - containerPort: 9888
          volumeMounts:
            - name: boot-config
              mountPath: /tmp
            - name: data
              mountPath: /opt/splunk/var
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPLUNK_BEFORE_START_CMD_1
              value: "version $SPLUNK_START_ARGS"
            - name: SPLUNK_BEFORE_START_CMD_2
              value: "cmd python /opt/splunk/bin/splunk_setup.py --wait-splunk 'https://master:8089' cluster_master"
            - name: SPLUNK_BEFORE_START_CMD_3
              value: "cmd python /opt/splunk/bin/splunk_setup.py --configure '/tmp/indexer.conf'"
            - name: SPLUNK_CMD_1
              value: "status"
            - name: SPLUNK_HEALTHCHECK_HEC
              value: "http://127.0.0.1:8088"
            - name: SPLUNK_HEALTHCHECK_SPLUNKD
              value: "https://127.0.0.1:8089"
            - name: SPLUNK_START_ARGS
              value: "--accept-license --answer-yes --no-prompt"
