apiVersion: v1
kind: Service
metadata:
  name: indexer-lb
  labels:
    app: splunk
    role: indexer
spec:
  type: LoadBalancer
  selector:
    app: splunk
    role: indexer
  ports:
    - name: http
      port: 80
      targetPort: 8088
