apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: splunk
    role: indexer
spec:
  clusterIP: None
  ports:
  - name: mgmt
    port: 8089
    targetPort: 8089
  - name: indexing
    port: 9997
    targetPort: 9997
  - name: replication
    port: 9888
    targetPort: 9888
  selector:
    app: splunk
    role: indexer
