apiVersion: v1
kind: Service
metadata:
  name: master
  labels:
    app: splunk
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: splunk
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: mgmt
      port: 8089
      targetPort: 8089
    - name: kv
      port: 8191
      targetPort: 8191
